config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'users/new' => 'users#new' , as: 'users_new'
  post 'users/create' => 'users#create' , as: 'users_create'
  get 'users/show/:id' => 'users#show', as: 'users_show'
  patch 'users/update/:id' => 'users#update', as: 'users_update'
  get 'users/index' => 'users#index', as: 'users_index'
  get 'users/edit/:id' => 'users#edit', as: 'users_edit'
  delete 'users/destroy/:id' => 'users#destroy', as: 'users_destroy'

  get 'login'     => 'sessions#new' , as: 'sessions_new'
  post 'login'    => 'sessions#create' , as: 'sessions_create'
  delete 'logout' => 'sessions#destroy'  , as: 'sessions_destroy'

  get 'pages/secret' => 'pages#secret', as: 'pages_secret'

  #books
  get 'books/new' => 'books#new', as: 'books_new'
  post 'books/create' => 'books#create', as: 'books_create'
  get 'books/show/:id' => 'books#show', as: 'books_show'
  get 'books/index' => 'books#index', as: 'books_index'
  get 'books/edit/:id' => 'books#edit', as: 'books_edit'
  patch 'books/update/:id' => 'books#update', as: 'books_update'
  get 'books/search' => 'books#search', as: 'books_search'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  REGISTER_UNIQUE = 'Insira uma matrícula que não foi' + \
                    ' cadastrada anteriormente'.freeze
  validates :name, presence: { message: 'Preencha o campo' }
  validates :class_code, presence: { message: 'Preencha o campo' }
  validates :register, presence: { message: 'Preencha o campo' }
  validates :register, uniqueness: { message: REGISTER_UNIQUE }
  validates :cpf, presence: { message: 'Preencha o campo' }
  validates :cpf, cpf: { message: 'Insira um CPF válido' }
  validates :cpf, uniqueness: { message: 'Não insira um CPF repetido' }
  validates :address, presence: { message: 'Preencha o campo' }
  validates :level, presence: { message: 'Preencha o campo' }

  validate :class_code_needs_a_number_and_a_caracter

  def class_code_needs_a_number_and_a_caracter
    return if class_code.nil?

    return if class_code.size == 2

    errors.add(:class_code, 'Ano e turma inválidos')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: %i[create new edit update]

  before_action :admin?, only: %i[destroy]
  def new
    @user = User.new
  end

  def index
    @users = User.all
  end

  def editadm
    @user = User.find_by(id: params['id'])
  end

  def show
    if current_user.level.zero?
      @user = User.find_by(id: params[:id])
      if @user.nil?
        flash.now.alert = 'Usuário não existente'
        index
        render :index
      end
    else
      @user = current_user
    end
  end

  def create
    user = User.new(permit)
    if user.save
      flash[:notice] = 'Criado com Sucesso!'
      redirect_to root_path
    else
      @msg = user.errors.messages
      flash.now.alert = @msg
      @user = User.new
      render :new
    end
  end

  def edit
    if current_user.level.zero?
      @user = User.find_by(id: params[:id])
      if @user.nil?
        flash.now.alert = 'Usuário não existente'
        index
        render :index
      end
    else
      @user = current_user
    end
  end

  def update
    @user = User.find_by(id: params['id'])
    if @user.update_attributes(permit)
      redirect_to pages_secret_path, notice: 'Alterado com sucesso!'
    else
      flash.now.alert = @user.errors.messages
      render :edit
    end
  end

  def destroy
    user = User.find_by(id: params[:id])
    if user
      user.destroy
      redirect_to pages_secret_path, notice: 'Removido com sucesso!'
    else
      flash.now.alert = 'Usuário não existente'
      render :index
    end
  end

  private

  def permit
    params['user'].permit(:name, :cpf, :address,
                          :register, :level, :class_code,
                          :password, :password_confirmation)
  end

  def user_params
    params.require('user').permit(:name, :cpf, :address,
                                  :register, :level, :class_code,
                                  :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<h1>Alterar Usuário</h1>
<%= form_for @user, url: users_update_path(@user) do |f|%>
  <%= f.label :name, 'Nome' %>
  <%= f.text_field :name %>
  <%= f.label :class_code, 'Turma' %>
  <%= f.text_field :class_code %>
  <%= f.label :register, 'Matrícula' %>
  <%= f.text_field :register %>
  <%= f.label :cpf, 'CPF' %>
  <%= f.text_field :cpf %>
  <%= f.label :address, 'Endereço' %>
  <%= f.text_field :address %>
  <%= f.label :password, 'Senha' %>
  <%= f.text_field :password %>
  <%= f.label :password_confirmation, 'Confirme a Senha' %>
  <%= f.text_field :password_confirmation %>
  <%= f.submit 'Enviar' %>
<%end%>

app/views/users/editadm.html.erb
<h1>Alterar Usuário</h1>
  <%= form_for @user, url: users_update_path(@user.id) do |f|%>
  <%= f.label :name, 'Nome:' %>
  <%= f.text_field :name %>
  <%= f.label :class_code, 'Turma:' %>
  <%= f.text_field :class_code %>
  <%= f.label :register, 'Matrícula:' %>
  <%= f.text_field :register %>
  <%= f.label :cpf, 'CPF:' %>
  <%= f.text_field :cpf %>
  <%= f.label :address, 'Endereço:' %>
  <%= f.text_field :address %>
  <%= f.label :password, 'Senha:' %>
  <%= f.text_field :password %>
  <%= f.label :password_confirmation, 'Confirmação da Senha:' %>
  <%= f.text_field :password_confirmation %>
  <%= f.label :level, 'É administrador:' %>
  <%= f.check_box :level, {}, "0", "1" %>
  <%= f.submit 'Enviar' %>
<%end%>

app/views/users/index.html.erb
<div class="card text-center">
  
<div class="card-header">
  <h1>Todos os usuários</h1>
</div>
	
<div class="card-header">
  <%= link_to 'Criar Novo usuário ?', users_new_path %>
</div>

  <% @users.each do |user| %>
	
<div class="row">
	
<div class="col-12 col-lg-4 col-sm-6">
		
<div class="card border-primary">

  <ul class="list-group list-group-flush">

    <li class="list-group-item"> Nome </li>
    <li class="list-group-item"> CPF </li>
    <li class="list-group-item"> Matrícula </li>
    <li class="list-group-item"> Turma </li>
    <li class="list-group-item"> Endereço </li>
    <li class="list-group-item"> Alterar </li>
    <li class="list-group-item"> Remover </li>

    <br>
			
  </ul>

</div>

</div>

<div class="col-12 col-lg-8 col-sm-6">
		
<div class="card border-primary">

  <ul class="list-group list-group-flush">

    <li class="list-group-item"> <%= link_to user.name, users_show_path(user.id)%> </li>
    <li class="list-group-item"> <%= link_to user.cpf, users_show_path(user.id) %> </li>
    <li class="list-group-item"> <%= link_to user.register, users_show_path(user.id)%> </li>
    <li class="list-group-item"> <%= link_to user.class_code, users_show_path(user.id)%> </li>
    <li class="list-group-item"> <%= link_to user.address, users_show_path(user.id)%> </li>
    <li class="list-group-item"> <%= link_to 'Alterar', users_edit_path(user.id)%> </li>
    <li class="list-group-item"> <%= link_to 'Remover', users_destroy_path(user.id), :method => 'delete'%> </li>

    <br>
			
  </ul>
					 
</div>

</div>

</div>

  <% end %>

</div>

app/views/users/index2.html.erb
<h1>Mostrar usuários</h1>

<table border='2px' style='width': 50%>
	<tr>
		<td>Nome</td>
		<td>CPF</td>
		<td>Matrícula</td>
		<td>Turma</td>
		<td>Endereço</td>
	</tr>

<tr>
		<td>@user.name</td>
		<td>@user.cpf</td>
		<td>@user.register</td>
		<td>@user.class_code</td>
		<td>@user.address</td>

</tr>
</table>

app/views/users/new.html.erb
<div class="card text-center">
  
<div class="card-header">
  <h1> Cadastro do Usuário </h1>
</div>
  
  <%= form_for @user, url:users_create_path do |f| %>
  
<div class="row">
	
<div class="col-12 col-lg-12 col-sm-6">
		
<div class="card">
          
<div class="card-header">
		  
  <%= f.label :name, 'Nome: '%>
  <%= f.text_field :name %>
  
  <br>
		  
</div>
		    
  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <%= f.label :class_code, 'Turma: ' %>
	  <%= f.text_field :class_code %>
	  <br>
    </li>
    <li class="list-group-item">
      <%= f.label :register, 'Matrícula: ' %>
      <%= f.text_field :register %>
      <br>
    </li>
    <li class="list-group-item">
      <%= f.label :cpf, 'CPF: ' %>
      <%= f.text_field :cpf %>
      <br>						  
    </li>
    <li class="list-group-item">
      <%= f.label :address, 'Endereço: ' %>
      <%= f.text_field :address %>
      <br>
      <br>				   
    </li>
    <li class="list-group-item">
      <%= f.label :password, 'Senha: ' %>
      <%= f.password_field :password %>
      <br>				   
    </li>
    <li class="list-group-item">
      <%= f.label :password_confirmation, 'Confirme a Senha: ' %>
      <%= f.password_field :password_confirmation %><br>		           
    </li>
    <li class="list-group-item">
      <%= f.submit 'Enviar' %>				   
    </li>
  </ul>
        
</div>

</div>
 
</div>

  <% end %>

app/views/users/show.html.erb
<div class="card text-center">
  
<div class="card-header">
  <h1>Mostrar perfil</h1>
</div>

<div class="row">
	
<div class="col-12 col-lg-4 col-sm-6">
		
<div class="card">
								
<div class="card-header">
  Nome
</div>
								
  <ul class="list-group list-group-flush">
    <li class="list-group-item">CPF</li>
    <li class="list-group-item">Matrícula</li>
    <li class="list-group-item">Ano</li>
    <li class="list-group-item">Turma</li>
    <li class="list-group-item">Origem</li>
    <li class="list-group-item">Quantidade</li>
    <li class="list-group-item">Endereço</li>
  </ul>
					 
</div>

<div class="col-12 col-lg-8 col-sm-6">
				 		
<div class="card">
				 								
<div class="card-header">									
  <%=@user.name%>				 								
</div>
				 		
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><%=@user.cpf%></li>
    <li class="list-group-item"><%=@user.register%></li>
    <li class="list-group-item"><%=@user.class_code%></li>
    <li class="list-group-item"><%=@user.address%></li>
  </ul>
				 					 
</div>

</div>
				 
</div>

</div>
				 
<br>
<br>