config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'users/new' => 'users#new' , as: 'users_new'
  post 'users/create' => 'users#create' , as: 'users_create'
  get 'users/show/:id' => 'users#show', as: 'users_show'
  patch 'users/update/:id' => 'users#update', as: 'users_update'
  get 'users/index' => 'users#index', as: 'users_index'
  get 'users/edit/:id' => 'users#edit', as: 'users_edit'
  delete 'users/destroy/:id' => 'users#destroy', as: 'users_destroy'

  get 'login'     => 'sessions#new' , as: 'sessions_new'
  post 'login'    => 'sessions#create' , as: 'sessions_create'
  delete 'logout' => 'sessions#destroy'  , as: 'sessions_destroy'

  get 'pages/secret' => 'pages#secret', as: 'pages_secret'

  #books
  get 'books/new' => 'books#new', as: 'books_new'
  post 'books/create' => 'books#create', as: 'books_create'
  get 'books/show/:id' => 'books#show', as: 'books_show'
  get 'books/index' => 'books#index', as: 'books_index'
  get 'books/edit/:id' => 'books#edit', as: 'books_edit'
  patch 'books/update/:id' => 'books#update', as: 'books_update'
  get 'books/search' => 'books#search', as: 'books_search'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    # empty method definitions
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<div class="container">

<div class="row my-4">
	  
<div class="col">

<div class="bd-example">
  	   
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">

  <ol class="carousel-indicators">
    <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"> </li>
    <li data-target="#carouselExampleCaptions" data-slide-to="1"> </li>
    <li data-target="#carouselExampleCaptions" data-slide-to="2"> </li>
  </ol>
            
<div class="carousel-inner">
                
<div class="carousel-item active">
                  
  <img src="https://image.freepik.com/fotos-gratis/grupo-de-pessoas-estudando-no-corredor_21730-8889.jpg" class="d-block w-100" alt="..." style="height:300px;">
                  
<div class="carousel-caption d-none d-md-block">
  
</div>
			       
</div>

<div class="carousel-item">
                  
  <img src="https://image.freepik.com/fotos-gratis/grupo-de-pessoas-estudando-no-corredor_21730-8889.jpg" class="d-block w-100" alt="..." style="height:300px;">
                  
<div class="carousel-caption d-none d-md-block">
  
</div>
			           
</div>
			           
<div class="carousel-item">
                  
  <img src="https://image.freepik.com/fotos-gratis/grupo-de-pessoas-estudando-no-corredor_21730-8889.jpg" class="d-block w-100" alt="..." style="height:300px;">
			              
<div class="carousel-caption d-none d-md-block">
			                
</div>
              
</div>
		          
</div>
        
  <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
        
  <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
      
</div>
    
</div>
		
</div>
 
</div>
	
<div class="row my-4">
  
<div class="col">
  <h1 style="text-align: center;"> Biblioteca Virtual CEMI </h1>
</div>
	
</div>
	
<div class="row">
  
<div class="col-7 mx-auto text-center">
			
  <%= form_tag books_search_path, method: 'get' do %>
  <%= text_field_tag 'search_term', nil, class: 'form-control', placeholder: 'Buscar' %>

<div class="col-2 my-3"></div>

  <%= submit_tag 'Buscar', class: 'btn btn-primary text-white'%>
  <% end %>
		
</div>

</div>

</div>

  <br>