config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'users/new' => 'users#new' , as: 'users_new'
  post 'users/create' => 'users#create' , as: 'users_create'
  get 'users/show/:id' => 'users#show', as: 'users_show'
  patch 'users/update/:id' => 'users#update', as: 'users_update'
  get 'users/index' => 'users#index', as: 'users_index'
  get 'users/edit/:id' => 'users#edit', as: 'users_edit'
  delete 'users/destroy/:id' => 'users#destroy', as: 'users_destroy'

  get 'login'     => 'sessions#new' , as: 'sessions_new'
  post 'login'    => 'sessions#create' , as: 'sessions_create'
  delete 'logout' => 'sessions#destroy'  , as: 'sessions_destroy'

  get 'pages/secret' => 'pages#secret', as: 'pages_secret'

  #books
  get 'books/new' => 'books#new', as: 'books_new'
  post 'books/create' => 'books#create', as: 'books_create'
  get 'books/show/:id' => 'books#show', as: 'books_show'
  get 'books/index' => 'books#index', as: 'books_index'
  get 'books/edit/:id' => 'books#edit', as: 'books_edit'
  patch 'books/update/:id' => 'books#update', as: 'books_update'
  get 'books/search' => 'books#search', as: 'books_search'

end

app/models/book.rb
class Book < ApplicationRecord
  before_validation do |doc|
    doc.bar_code = doc.generate_bar_code
  end

  validates :title, presence: { message: 'Preencha o campo' }
  validates :author, presence: { message: 'Preencha o campo' }
  validates :publishing_company, presence: { message: 'Preencha o campo' }
  validates :year, presence: { message: 'Preencha o campo' }
  validates :category, presence: { message: 'Preencha o campo' }
  validates :bar_code, presence: { message: 'Preencha o campo' }
  validates :bar_code, uniqueness: { message: 'Insira outro código de barra' }
  validates :source_of_donation, presence: { message: 'Preencha o campo' }
  validates :amount, presence: { message: 'Preencha o campo' }

  def generate_bar_code
    require 'digest'
    loop do
      code = []
      12.times do
        code.push([*('1'..'9')].sample)
      end
      bar_code = code.join
      break bar_code if Book.find_by(bar_code: bar_code).nil?
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :admin?, only: %i[edit new create update]
  require 'barby'
  require 'barby/barcode/ean_13'
  require 'barby/outputter/html_outputter'

  def new
    @book = Book.new
  end

  def index
    @books = Book.all
  end

  def search
    term = params[:search_term]
    @books = Book.where('title like ? OR bar_code = ?', "%#{term}%", term)
  end

  def edit
    @book = Book.find_by(id: params['id'])
  end

  def show
    @book = Book.find_by(id: params['id'])
    @barcode = Barby::EAN13.new(@book.bar_code)
    @barcode_for_html = Barby::HtmlOutputter.new(@barcode)
  end

  def create
    book = Book.new(permit)
    if book.save
      flash[:notice] = 'Cadastrado com Sucesso!'
      redirect_to root_path
    else
      @msg = book.errors.messages
      flash.now.alert = 'Não foi possível cadastrar.'
      render :new
    end
  end

  def update
    @book = Book.find_by(id: params['id'])
    if @book.update_attributes(permit)
      redirect_to pages_secret_path, notice: 'Alterado com sucesso!'
    else
      flash.now.alert = @book.errors.messages
      render :edit
    end
  end

  private

  def permit
    params['book'].permit(:title, :author, :publishing_company, :year)
    params['book'].permit(:category, :bar_code, :source_of_donation, :amount)
  end

  def book_params
    params.require('book').permit(:title, :author, :publishing_company,
                                  :year, :category,
                                  :source_of_donation, :amount)
  end
end

app/views/books/create.html.erb
<h1><%= @msg %></h1>

app/views/books/edit.html.erb
<h1>Alterar Dados do Livro</h1>
  <%= form_for @book, url: books_update_path(@book.id) do |f|%>
  <%= f.label :title, 'Título:' %>
  <%= f.text_field :title %>
  <%= f.label :author, 'Autor:' %>
  <%= f.text_field :author %>
  <%= f.label :publishing_company, 'Editora:' %>
  <%= f.text_field :publishing_company %>
  <%= f.label :year, 'Ano:' %>
  <%= f.text_field :year %>
  <%= f.label :category, 'Categoria:' %>
  <%= f.text_field :category %>
  <%= f.label :source_of_donation, 'Origem da Doação:' %>
  <%= f.text_field :source_of_donation %>
  <%= f.label :amount, 'Quantidade:' %>
  <%= f.text_field :amount %>
  <%= f.submit 'Salvar' %>
  <%end%>

app/views/books/index.html.erb
<div class="card text-center">

<div class="card-header">
  <h1> Todos os livros </h1>
</div>

<form class="" action="search.html.erb" method="post">
  Buscar <input type="text" name="searching" >
</form>

<div class="row">

<div class="col-12 col-lg-4 col-sm-6">

<div class="card">

<div class="card-header">
  Nome do Livro
</div>
 
  <ul class="list-group list-group-flush">
    <li class="list-group-item"> Autor </li>
    <li class="list-group-item"> Ano </li>
    <li class="list-group-item"> Alterar </li>
    <li class="list-group-item"> Remover </li>
  </ul>

</div>

</div>

<div class="col-12 col-lg-8 col-sm-6">

<div class="card">
 
  <% @books.each do |book| %>

<div class="card-header">
  <% @books.each do |book| %>
  <%= link_to book.title, books_show_path(book.id) %>
</div>
 
  <ul class="list-group list-group-flush">
    <li class="list-group-item"> <%= link_to book.author, books_show_path(book.id)%> </li>
    <li class="list-group-item"> <%= link_to book.year, books_show_path(book.id)%> </li>
    <li class="list-group-item"> <%= link_to 'Alterar', books_edit_path(book.id) %> </li>
    <li class="list-group-item"> <%= link_to 'Remover', sessions_destroy_path(book.id), :method => 'delete' %> </li>
  </ul>
  
</div>

</div>

</div>

</div>

<br>
<br>
<% end %>
<% end %>

app/views/books/new.html.erb
<div class="card text-center">
 
<div class="card-header">
  <h1> Cadastro de Livros </h1>
</div>
 
  <%= form_for @book , url:books_create_path do |f| %>

<div class="row">

<div class="col-12 col-lg-12 col-sm-6">

<div class="card">

<div class="card-header">
  <%= f.label :title, 'Nome do Livro:' %>
  <%= f.text_field :title %>
</div>

  <ul class="list-group list-group-flush">
   
    <li class="list-group-item">
      <%= f.label :author, 'Autor:' %>
      <%= f.text_field :author %>
    </li>
    
    <li class="list-group-item">
      <%= f.label :publishing_company, 'Editora:' %>
      <%= f.text_field :publishing_company %>
    </li>
                  
    <li class="list-group-item">
      <%= f.label :year, 'Ano:' %>
      <%= f.text_field :year %>
    </li>

    <li class="list-group-item">
      <%= f.label :category, 'Categoria:' %>
      <%= f.text_field :category %>
    </li>

    <li class="list-group-item">
      <%= f.label :source_of_donation, 'Origem da Doação:' %>
      <%= f.text_field :source_of_donation %>
    </li>
											
    <li class="list-group-item">
      <%= f.label :amount, 'Quantidade:' %>
      <%= f.text_field :amount %>
    </li>

    <li class="list-group-item btn border-sucess">
      <%= f.submit 'Salvar' %>
    </li>

  </ul>

</div>

</div>

<% end %>

app/views/books/search.html.erb
<h1> Todos os livros </h1>

  <form class="" method="post">
    Buscar <input type="text" name="searching">
  </form>
  
    <table border='2px' style='width': 50%>
     
      <tr>
        <td> Título </td>
		<td> Autor </td>
		<td> Ano </td>
		<td> Quantidade </td>
	  </tr>
	  
<% @books.each do |book| %>

      <tr>
        <td> <%= link_to book.title, books_show_path(book.id)%> </td>
		<td> <%= link_to book.author, books_show_path(book.id)%> </td>
        <td> <%= link_to book.year, books_show_path(book.id)%> </td>
        <td> <%= link_to book.amount, books_show_path(book.id)%> </td>
      </tr>
      
<% end %>
   
    </table>

app/views/books/seebook.html.erb
<h1> Informações Gerais do Livro </h1>

  <table border='2px' style='width': 50%>
   
    <tr>
      <td> Título </td>
      <td> Autor </td>
      <td> Quantidade </td>
      <td> Editora </td>
      <td> Categoria </td>
      <td> Ano </td>
      <td> Código de Barras </td>
      <td> Origem da Doação </td>
	</tr>

    <tr>
      <td> <%=@book.title%> </td>
	  <td> <%=@book.author%> </td>
	  <td> <%=@book.amount%> </td>
	  <td> <%=@book.publishing_company%> </td>
	  <td> <%=@book.category%> </td>
	  <td> <%=@book.year%> </td>
	  <td> <%=@book.bar_code%> </td>
	  <td> <%=@book.source_of_donation%> </td>
    </tr>
    
  </table>

app/views/books/show.html.erb
<div class="card text-center">
 
<div class="card-header">
  <h1> Mostrar Livros </h1>
</div>

<div class="row">

<div class="col-12 col-lg-4 col-sm-6">
		
<div class="card">

<div class="card-header">
  Nome do Livro
</div>

  <ul class="list-group list-group-flush">
    <li class="list-group-item"> Autor </li>
    <li class="list-group-item"> Editora </li>
    <li class="list-group-item"> Ano </li>
    <li class="list-group-item"> Categoria </li>
    <li class="list-group-item"> Origem </li>
    <li class="list-group-item"> Quantidade </li>
    <li class="list-group-item"> Código de Barras </li>
  </ul>
		
</div>

</div>

<div class="col-12 col-lg-8 col-sm-6">
		
<div class="card">
      
<div class="card-header">
  <%= @book.title %>
</div>
        
  <ul class="list-group list-group-flush">
   
    <li class="list-group-item"> <%= @book.author %> </li>
    <li class="list-group-item"> <%= @book.publishing_company %> </li>
    <li class="list-group-item"> <%= @book.year %> </li>
    <li class="list-group-item"> <%= @book.category %> </li>
    <li class="list-group-item"> <%= @book.source_of_donation %> </li>
    <li class="list-group-item"> <%= @book.amount %> </li>
    <li class="list-group-item text-center"> 
      <%= raw @barcode_for_html.to_html %>
      <br>
      Código: <%= @book.bar_code %> 
    </li>
    
  </ul>
  
</div>

</div>

</div>

</div>

  <br>
  <br>
  
<style>

  table.barby-barcode {
    border-spacing: 0; margin: auto; 
  }
  
  tr.barby-row {
    
  }
  
  td.barby-cell {
    width: 3px; height: 100px; 
  }
  
  td.barby-cell.on { 
    background: #000; 
  }

</style>