config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  get 'users/new' => 'users#new' , as: 'users_new'
  post 'users/create' => 'users#create' , as: 'users_create'
  get 'users/show/:id' => 'users#show', as: 'users_show'
  patch 'users/update/:id' => 'users#update', as: 'users_update'
  get 'users/index' => 'users#index', as: 'users_index'
  get 'users/edit/:id' => 'users#edit', as: 'users_edit'
  delete 'users/destroy/:id' => 'users#destroy', as: 'users_destroy'

  get 'login'     => 'sessions#new' , as: 'sessions_new'
  post 'login'    => 'sessions#create' , as: 'sessions_create'
  delete 'logout' => 'sessions#destroy'  , as: 'sessions_destroy'

  get 'pages/secret' => 'pages#secret', as: 'pages_secret'

  #books
  get 'books/new' => 'books#new', as: 'books_new'
  post 'books/create' => 'books#create', as: 'books_create'
  get 'books/show/:id' => 'books#show', as: 'books_show'
  get 'books/index' => 'books#index', as: 'books_index'
  get 'books/edit/:id' => 'books#edit', as: 'books_edit'
  patch 'books/update/:id' => 'books#update', as: 'books_update'
  get 'books/search' => 'books#search', as: 'books_search'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Biblioteca </title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body style="background-color: #D8D8D8;">

  <div class="row">
            
  <div class="col">
                
  <div class="top-menu">
                  
    <nav>
      <ul>
        <% if current_user %>
        <li> <%= "Logado como #{current_user.name}" %> </li> 
        <li> <%= link_to 'Início', root_path %> </li> 
        <li> <%= link_to 'Editar', users_edit_path(current_user.id) %> </li>
        <li> <%= link_to 'Mostrar Perfil', users_show_path(current_user.id) %> </li>
    </nav>
                  
    <nav>
      <ul class="login">
      <!-- current_user will return true if a user is logged in -->
        <li> <%= link_to 'Sair', sessions_destroy_path, method: :delete %> </li>
    </nav>
    
  </div>
                  
  </div>
                  
  </div>
                
  <br>

    <% if current_user.level == 0 %>
    
  <div class="row">
        
  <div class="col-6 mx-auto">
         
  <div class="card text-center ">
              
  <div class="card-header">
    <h2> Você é um administrador</h2>
  </div>
  
  <div class="card-body">
      
    <ul>
      <i class="btn border-primary"> <%= link_to 'Mostrar todos', users_index_path %> </i> 
      <li class="btn  border-primary"> <%= link_to 'Cadastrar Livros', books_new_path %> </li> 
      <li class="btn  border-primary"> <%= link_to 'Mostrar Acervo', books_index_path %> </li>
    </ul>
                
  </div>
  
  <div class="card-footer">
    <h6> Haja como tal </h6>
  </div>
       
  </div>
        
  </div>
        
  </div>
      
    <% end %>
    <%else%>
    
  <div class="row">
             
  <div class="col">
                  
  <div class="top-menu">
                    
    <nav>
      <ul>
        <li> 
          <%= link_to 'Login', sessions_create_path %></li> |
        <li>
          <%= link_to 'Cadastre-se', users_new_path %>
        </li>
    </nav>
    
    <nav>
      <ul class="login">
        <li> <%= link_to 'Cadastre-se', users_new_path %> </li>
      </ul>
    </nav>
                  
  </div>
              
  </div>
          
  </div>

  <hr>
      
    <% end %>

  <hr>

    <% if notice %>
    <%= notice %>
    <% end %>

    <% if alert %>
    <%= alert %>
    <% end %>

    <%= yield %>

    <footer id="myFooter">
    
  <div class="container">
           
  <div class="row">
                
  <div class="col-sm-3">
                
    <h2 class="logo">
      <%= image_tag('bibliotecavirtual.png', style: 'width:200px; heigth:200px;') %>
    </h2>
               
  </div>
                
  <div class="col-sm-2">
                    
    <h5> Começando </h5>
    <ul>
      <li> <a href="#"> Inicio </a> </li>
      <li> <a href="#"> Cadastro </a> </li>
    </ul>
      
  </div>
                
  <div class="col-sm-2">
                   
    <h5> Sobre nós </h5>                
    <ul>
      <li> <a href="#"> CEMI </a> </li>
      <li> <a href="#"> Contato </a> </li>
    </ul>
    
  </div>
               
  <div class="col-sm-2">
    <h5> Suporte </h5>
    <ul>
      <li> <a href="#"> FAQ </a> </li>
      <li> <a href="#"> Email </a> </li>
      <li> <a href="#"> Forums </a> </li>
    </ul>
  </div>
                
  <div class="col-sm-3">
                   
  <div class="social-networks">
    <a href="#" class="twitter"> <i class="fa fa-twitter"> </i> </a>
    <a href="#" class="facebook"> <i class="fa fa-facebook"> </i> </a>
    <a href="#" class="google"> <i class="fa fa-google-plus"> </i> </a>              
  </div>
                    
  <button type="button" class="btn btn-default"> Contate-nos </button>
                
  </div>
  
  </div>
        
  </div>
        
  <div class="footer-copyright">
    <p> © 2019 Copyright </p>      
  </div>
    
    </footer>

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"> </script>
      
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"> </script>
      
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"> </script>
      
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"> </script>
      
      <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"> </script>
  
</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title> Biblioteca </title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>

<body style="background-color: #D8D8D8;">

  <div class="row">
  
  <div class="col">
  
  <div class="top-menu">
                  
  <nav>
    <ul>
      <li> <%= link_to 'Login', sessions_create_path %> </li> |
      <li> <%= link_to 'Cadastre-se', users_new_path %> </li>
  </nav>
  
  <nav>
    <ul class="login">
      <li> <%= link_to 'Cadastre-se', users_new_path %> </li>
    </ul>
  </nav>
      
  </div>
            
  </div>
        
  </div>

  <hr>

    <% if notice %>
    <%= notice %>
    <% end %>

    <% if alert %>
    <%= alert %>
    <% end %>


    <%= yield %>

    <footer id="myFooter">
        
    <div class="container">
            
    <div class="row">
                
    <div class="col-sm-3">
      <h2 class="logo">
        <%= image_tag('bibliotecavirtual.png', style: 'width:200px; heigth:200px;') %>
      </h2>
    </div>
               
    <div class="col-sm-2">            
      <h5> Começando </h5>           
        <ul>
          <li> <a href="#"> Inicio </a> </li>
          <li> <a href="#"> Cadastro </a> </li>
        </ul>        
    </div>
    
    <div class="col-sm-2">             
      <h5> Sobre nós </h5>
        <ul>
          <li><a href="#">CEMI</a></li>
          <li><a href="#">Contato</a></li>
        </ul>      
    </div>
                
    <div class="col-sm-2">
      <h5>Suporte</h5>
        <ul>
          <li> <a href="#"> FAQ </a> </li>
          <li> <a href="#"> Email </a> </li>
          <li> <a href="#"> Forums </a> </li>
        </ul>
    </div>
                
    <div class="col-sm-3">
                    
    <div class="social-networks">
                       
      <a href="#" class="twitter"> <i class="fa fa-twitter"> </i> </a>
      <a href="#" class="facebook"> <i class="fa fa-facebook"> </i> </a>
      <a href="#" class="google"> <i class="fa fa-google-plus"> </i> </a>
      
    </div>
                   
      <button type="button" class="btn btn-default"> Contate-nos </button>
                
    </div>
            
    </div>
       
    </div>
        
    <div class="footer-copyright">
    
      <p> © 2019 Copyright </p>
        
    </div>
      
    </footer>

      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"> </script>
    
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"> </script>
    
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"> </script>
      
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"> </script>
    
      <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"> </script>
      
</body>

</html>